services:
  postgres:
    image: postgres:15
    container_name: labubu_postgres
    environment:
      POSTGRES_DB: labubu_db
      POSTGRES_USER: labubu_user
      POSTGRES_PASSWORD: super_secret_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data: